baseurl = "shesmyot.com.au"
languageCode = "en-us"
theme = "hugo-elate-theme"
title = "She's My OT"
[params]
author = ""
custom_css = ["css/custom1.css", "css/custom2.css"]
description = ""
email = "jess@shesmyot.com.au"
googleMapsApiKey = "AIzaSyD5488jtih9neHSUuD8upfwrQRvigzJGDM"
[params.about]
description = "There is nothing like staying at home for real comfort. --Jane Austen"
enable = true
title = "About"
[[params.about.item]]
alt = "Jessica Aya"
description = "Jess is an extremely passionate OT who puts her client's well-being above all else and is going into her 17th year as an Occupational Therapist.  She has worked in a variety of settings including Acute Care (ICU, Orthopaedics, Amputees, Neuro, and Oncology), Outpatient Rehabilitation (Lymphoedema, Upper-limb / hands), and Community Health."
img = "jess-circle.png"
name = "Jessica Aya"
position = "Occupational Therapist<br>James Cook University, 2004"
social = [["icon-linkedin", "https://www.linkedin.com/in/jessicaaya"]]
[params.contact]
button = "Send message"
description = "Please feel free to contact me via any of the methods below with any question big or small."
details = [["icon-clock", "Hours:  M-W, 9a-3p"], ["icon-phone", "+61 402 444 890"], ["icon-envelope", "jess@shesmyot.com.au"], ["icon-globe", "<a href=\"https://shesmyot.com.au/\" target=\"_blank\">shesmyot.com.au</a>"], ["icon-home", "P.O. Box 145, Samford Village, QLD 4520"]]
email = "Email"
enable = true
form = true
map = true
message = "Message"
name = "Name"
phone = "Phone"
title = "Got Questions?"
[params.counters]
background = "full_image_1.jpg"
enable = true
title = "Stats"
[[params.counters.item]]
description = "Years Experience"
from = 0
icon = "icon-briefcase"
interval = 100
speed = 1500
to = 15
[[params.counters.item]]
description = "Cups of tea"
from = 0
icon = "icon-cup"
interval = 25
speed = 15000
to = 21900
[[params.counters.item]]
description = "Happy Clients"
from = 0
icon = "icon-people"
interval = 50
speed = 3000
to = 200
[[params.counters.item]]
description = "Warm Smiles"
from = 0
icon = "icon-emotsmile"
interval = 50
speed = 7500
to = 986499
[params.footer]
copyright = "&copy; She's My OT.  All Rights Reserved."
enable = true
links = []
[params.hero]
subtitle = "Occupational Therapy"
title = "Logo"
[params.intro]
item = []
[params.navigation]
about = "About"
brand = ""
contact = "Contact"
home = "Home"
services = "Services"
testimonials = "Testimonials"
work = "Work"
[params.services]
description = "Providing person-centered, in-home Occupational Therapy services with â™¥"
enable = true
title = "Services"
[[params.services.item]]
description = "Your OT will complete an initial assessment and followup interventions to prevent falls, increase accessibility, and to promote and maintain your independence at home."
icon = "icon-home"
title = "Home Safety Assessments"
[[params.services.item]]
description = "After your initial assessment, recommedations may be made for equipment to enable you to keep living the life you wish to live.  Utilizing a range of equipment suppliers allows me to ensure you get the right piece of equipment for YOU."
icon = "icon-puzzle"
title = "Adaptive Equipment"
[[params.services.item]]
description = "Feeling unsafe in the shower?  Can't get that walker up and over that door threshold?  There's a rail and ramp for that!  I can prescribe home modifications and refer to your local Home Assist, or a qualified mobility and access builder."
icon = "icon-wrench"
title = "Home Modifications"
[[params.services.item]]
description = "As a certified Lymphoedema Therapist, I can work with your GP to assist in the management of your Lymphoedema through the treatment protocol of manual lymphatic drainage, bandaging, and compression garment prescriptions."
icon = "icon-drop"
title = "Lymphoedema Treatment and Management"
